CachSangTaoCuaNguoiN = `
﻿[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1280
PlayResY: 720

[Aegisub Project Garbage]
Audio File: CachSangTaoCuaNguoiNhat.mp4
Video File: CachSangTaoCuaNguoiNhat.mp4
Video AR Mode: 4
Video AR Value: 1.777778
Video Zoom Percent: 0.375000
Scroll Position: 73
Active Line: 84
Video Position: 10617

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:15.80,0:00:20.73,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:00:20.73,0:00:27.13,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:00:27.13,0:00:34.36,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:00:34.36,0:00:39.36,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:00:39.36,0:00:44.36,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:00:44.36,0:00:49.36,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:00:49.36,0:00:54.36,Default,,0,0,0,, sssssssssssss1111199999999999
Dialogue: 0,0:00:54.36,0:01:05.20,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:01:05.20,0:01:18.16,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:01:18.16,0:01:24.43,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:01:24.43,0:01:29.43,Default,,0,0,0,, sssssssssssss
Dialogue: 0,0:01:29.43,0:01:34.43,Default,,0,0,0,, 111sssssssssssss
Dialogue: 0,0:01:34.43,0:01:42.50,Default,,0,0,0,, 111sssssssssssss
Dialogue: 0,0:01:42.50,0:01:50.56,Default,,0,0,0,, 111sssssssssssss
Dialogue: 0,0:01:51.06,0:01:59.13,Default,,0,0,0,, 111sssssssssssss
Dialogue: 0,0:01:59.13,0:02:05.33,Default,,0,0,0,,
Dialogue: 0,0:02:05.33,0:02:10.33,Default,,0,0,0,,
Dialogue: 0,0:02:10.33,0:02:14.46,Default,,0,0,0,,
Dialogue: 0,0:02:14.46,0:02:19.46,Default,,0,0,0,,
Dialogue: 0,0:02:19.46,0:02:24.46,Default,,0,0,0,,
Dialogue: 0,0:02:24.46,0:02:29.46,Default,,0,0,0,,
Dialogue: 0,0:02:29.46,0:02:34.46,Default,,0,0,0,,
Dialogue: 0,0:02:34.46,0:02:39.46,Default,,0,0,0,,
Dialogue: 0,0:02:39.46,0:02:44.46,Default,,0,0,0,,
Dialogue: 0,0:02:44.46,0:02:49.46,Default,,0,0,0,,
Dialogue: 0,0:02:49.46,0:02:54.46,Default,,0,0,0,,
Dialogue: 0,0:02:54.46,0:02:59.46,Default,,0,0,0,,
Dialogue: 0,0:02:59.46,0:03:04.46,Default,,0,0,0,,
Dialogue: 0,0:03:04.46,0:03:09.46,Default,,0,0,0,,
Dialogue: 0,0:03:09.46,0:03:14.46,Default,,0,0,0,,
Dialogue: 0,0:03:14.46,0:03:19.46,Default,,0,0,0,,
Dialogue: 0,0:03:19.46,0:03:24.46,Default,,0,0,0,,
Dialogue: 0,0:03:24.46,0:03:29.46,Default,,0,0,0,,
Dialogue: 0,0:03:29.46,0:03:34.46,Default,,0,0,0,,
Dialogue: 0,0:03:34.46,0:03:39.46,Default,,0,0,0,,
Dialogue: 0,0:03:39.46,0:03:44.46,Default,,0,0,0,,
Dialogue: 0,0:03:44.46,0:03:49.46,Default,,0,0,0,,
Dialogue: 0,0:03:49.46,0:03:54.46,Default,,0,0,0,,
Dialogue: 0,0:03:54.46,0:03:59.46,Default,,0,0,0,,
Dialogue: 0,0:03:59.46,0:04:04.46,Default,,0,0,0,,
Dialogue: 0,0:04:04.46,0:04:09.46,Default,,0,0,0,,
Dialogue: 0,0:04:09.46,0:04:14.46,Default,,0,0,0,,
Dialogue: 0,0:04:14.46,0:04:19.46,Default,,0,0,0,,
Dialogue: 0,0:04:19.46,0:04:24.46,Default,,0,0,0,,
Dialogue: 0,0:04:24.46,0:04:29.46,Default,,0,0,0,,
Dialogue: 0,0:04:29.46,0:04:34.46,Default,,0,0,0,,
Dialogue: 0,0:04:34.46,0:04:39.46,Default,,0,0,0,,
Dialogue: 0,0:04:39.46,0:04:44.46,Default,,0,0,0,,
Dialogue: 0,0:04:44.46,0:04:49.46,Default,,0,0,0,,
Dialogue: 0,0:04:49.46,0:04:54.46,Default,,0,0,0,,
Dialogue: 0,0:04:54.46,0:04:59.46,Default,,0,0,0,,
Dialogue: 0,0:04:59.46,0:05:04.46,Default,,0,0,0,,
Dialogue: 0,0:05:04.46,0:05:09.46,Default,,0,0,0,,
Dialogue: 0,0:05:09.46,0:05:14.46,Default,,0,0,0,,
Dialogue: 0,0:05:14.46,0:05:19.46,Default,,0,0,0,,
Dialogue: 0,0:05:19.46,0:05:24.46,Default,,0,0,0,,
Dialogue: 0,0:05:24.46,0:05:29.46,Default,,0,0,0,,
Dialogue: 0,0:05:29.46,0:05:34.46,Default,,0,0,0,,
Dialogue: 0,0:05:34.46,0:05:39.46,Default,,0,0,0,,
Dialogue: 0,0:05:39.46,0:05:44.46,Default,,0,0,0,,
Dialogue: 0,0:05:44.46,0:05:49.46,Default,,0,0,0,,
Dialogue: 0,0:05:49.46,0:05:54.46,Default,,0,0,0,,
Dialogue: 0,0:05:54.46,0:05:59.46,Default,,0,0,0,,
Dialogue: 0,0:05:59.46,0:06:04.46,Default,,0,0,0,,
Dialogue: 0,0:06:04.46,0:06:09.46,Default,,0,0,0,,
Dialogue: 0,0:06:09.46,0:06:14.46,Default,,0,0,0,,
Dialogue: 0,0:06:14.46,0:06:19.46,Default,,0,0,0,,
Dialogue: 0,0:06:19.46,0:06:24.46,Default,,0,0,0,,
Dialogue: 0,0:06:24.46,0:06:29.46,Default,,0,0,0,,
Dialogue: 0,0:06:29.46,0:06:34.46,Default,,0,0,0,,
Dialogue: 0,0:06:34.46,0:06:39.46,Default,,0,0,0,,
Dialogue: 0,0:06:39.46,0:06:44.46,Default,,0,0,0,,
Dialogue: 0,0:06:44.46,0:06:49.46,Default,,0,0,0,,
Dialogue: 0,0:06:49.46,0:06:54.46,Default,,0,0,0,,
Dialogue: 0,0:06:54.46,0:06:59.46,Default,,0,0,0,,
Dialogue: 0,0:06:59.46,0:07:04.46,Default,,0,0,0,,
Dialogue: 0,0:07:04.46,0:07:09.46,Default,,0,0,0,,
Dialogue: 0,0:07:09.46,0:07:14.46,Default,,0,0,0,,
Dialogue: 0,0:07:14.46,0:07:19.46,Default,,0,0,0,,
Dialogue: 0,0:07:19.46,0:07:24.46,Default,,0,0,0,,
Dialogue: 0,0:07:24.46,0:07:29.46,Default,,0,0,0,,
Dialogue: 0,0:07:29.46,0:07:34.46,Default,,0,0,0,,
Dialogue: 0,0:07:34.46,0:07:39.46,Default,,0,0,0,,
Dialogue: 0,0:07:39.46,0:07:44.46,Default,,0,0,0,,
Dialogue: 0,0:07:44.46,0:07:49.46,Default,,0,0,0,,

`
